// Fill out your copyright notice in the Description page of Project Settings.


#include "InteractionSystem/InteractiveBoxComponent.h"

UInteractiveBoxComponent::UInteractiveBoxComponent()
{
    PrimaryComponentTick.bCanEverTick = true;
    PrimaryComponentTick.TickInterval = 0.25;
}

void UInteractiveBoxComponent::BeginPlay()
{
    Super::BeginPlay();

}

void UInteractiveBoxComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
    Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

}
