// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "MyBlueprintFunctionLibrary.generated.h"

/**
 * 
 */
UCLASS()
class HOWLING_API UMyBlueprintFunctionLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable, DisplayName = "Unregister Component From Owner", Category = "Components")
	static void UnregisterComponentFromOwner(UActorComponent* Component);

	UFUNCTION(BlueprintCallable)
	static void ClientTravel(APlayerController* PlayerController, FString LevelName, ETravelType TravelType);

	UFUNCTION(BlueprintPure, Category = "Actor")
	static bool IsActorOwnedByActor(AActor* Actor, AActor* OwningActor);

};
